### ISSUE TITLE
Can't return a Spec from validate_spec

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/scanspec#1]
At the moment we can do:

```
$ pipenv run scanspec service
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```
Then open http://localhost:8080/graphql?query=query%20%7B%0A%20%20validateSpec(spec%3A%20%7BBoundedLine%3A%20%7Bkey%3A%20%22X%22%2C%20lower%3A%200%2C%20upper%3A%201%2C%20num%3A%205%7D%7D)%0A%7D 
And we get:
```
{
  "data": {
    "validateSpec": "Line(key='X', start=0.1, stop=0.9, num=5)"
  }
}
```
This is because we defined https://github.com/dls-controls/scanspec/blob/182b8b43f0ff43731b65680969a6794eb4c4f85b/scanspec/service.py#L8-L10 to return a `str`. If we make it return a `Spec` then we get an error message `Type Spec must define one or more fields.`.

My guess is that if you define a `serializer` as well as a `deserializer` in https://github.com/dls-controls/scanspec/blob/apischema-3.7/scanspec/core.py#L111-L115 then it might just work...

**Comment by EmmaCD** [comment]
Attempting to define a serializer here is what got me into the infinite recursion issue when a field of a Spec is also a Spec. If there's a way to register these serializers here and not run into that problem then it will also allow getting rid of the hacking of the metadata to add dynamic conversions which would be nice.

**Comment by thomascobb** [comment]
Actually, we don't really want the GraphQL structure out, otherwise the client would have to request the bits it wanted, which kinda defeats the whole purpose. Turns out that `Any` maps to JSON, who knew?
https://github.com/dls-controls/scanspec/commit/24b014beca8927c9244ea15fa020cd2896348e67
This means we get what we want:
```
{
  "data": {
    "validateSpec": {
      "Line": {
        "key": "X",
        "start": 0.1,
        "stop": 0.9,
        "num": 5
      }
    }
  }
}
```
So no automatic serializer needed...
