### ISSUE TITLE
Think about whether key is an id

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/scanspec#16]
At the moment key is an Any type. This is so we can pass motor Devices when used on the commandline. The GraphQL interface maps this to a JSON type, which we map to string on the Java side. This is probably ok, but maybe we should consider using a GraphQL id type?
https://wyfo.github.io/apischema/graphql/data_model_and_resolvers/#id-encoding

This is one to think about when we've done the bluesky integration

**Comment by MichaelStubbings** [comment]
Note: 'Key/keys' has since been update to 'axis/axes' with a new String type since issue: https://github.com/dls-controls/scanspec/pull/17
