### ISSUE TITLE
Add __all__ to all the public modules

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/scanspec#6]
Anything that appears in the docs should be in the `__all__` for its module. This should appear at the top of the module.
For instance in spec.py we should have at least:
```python
__all__ = [
   ...
    "Line",
    "Spiral",
    ...
]
```

**Comment by MichaelStubbings** [comment]
In line with pull request: https://github.com/dls-controls/scanspec/pull/17 I have created '__all__' lists in every relevant source file determined by the API section of the documentation. I suggest that the issue be reviewed in the next version of the pull request and closed if satisfactory.
