### ISSUE TITLE
Support matplotlib>=3.6

### ISSUE THREAD

**Issue by callumforrester** [dls-controls/scanspec#61]
Currently some of the plotting tests fail
```shell
====================================================================== FAILURES =======================================================================
____________________________________________________________ test_plot_2D_line_rect_region ____________________________________________________________
Traceback (most recent call last):
  File "/home/vid18871/projects/scanspec/tests/test_cli.py", line 148, in test_plot_2D_line_rect_region
    assert result.exit_code == 0
AssertionError: assert 1 == 0
 +  where 1 = <Result MatplotlibDeprecationWarning('Passing the angle parameter of __init__() positionally is deprecated since Matplotlib 3.6; the parameter will become keyword-only two minor releases later.')>.exit_code
__________________________________________________________________ test_plot_3D_line __________________________________________________________________
Traceback (most recent call last):
  File "/home/vid18871/projects/scanspec/tests/test_cli.py", line 216, in test_plot_3D_line
    assert len(arrow_artists) == 4
AssertionError: assert 0 == 4
 +  where 0 = len([])
```

**Comment by coretl** [comment]
@tizayi

**Comment by tizayi** [comment]
for the test test_plot_3D_line.


get_default_bbox_extra_artists()  which is used in the test was changed in between matplotlib 3.5.3 and 3.60. 

in 3.53
`
    def get_default_bbox_extra_artists(self):
        """
        Return a default list of artists that are used for the bounding box
        calculation.

        Artists are excluded either by not being visible or
        ``artist.set_in_layout(False)``.
        """

        artists = self.get_children()

        if not (self.axison and self._frameon):
            # don't do bbox on spines if frame not on.
            for spine in self.spines.values():
                artists.remove(spine)

        if not self.axison:
            for _axis in self._get_axis_list():
                artists.remove(_axis)

        artists.remove(self.title)
        artists.remove(self._left_title)
        artists.remove(self._right_title)

        return [artist for artist in artists
                if (artist.get_visible() and artist.get_in_layout())]
`

and in 3.60
`
    def get_default_bbox_extra_artists(self):
        """
        Return a default list of artists that are used for the bounding box
        calculation.

        Artists are excluded either by not being visible or
        ``artist.set_in_layout(False)``.
        """

        artists = self.get_children()

        for axis in self._axis_map.values():
            # axis tight bboxes are calculated separately inside
            # Axes.get_tightbbox() using for_layout_only=True
            artists.remove(axis)
        if not (self.axison and self._frameon):
            # don't do bbox on spines if frame not on.
            for spine in self.spines.values():
                artists.remove(spine)

        artists.remove(self.title)
        artists.remove(self._left_title)
        artists.remove(self._right_title)

        # always include types that do not internally implement clipping
        # to Axes. may have clip_on set to True and clip_box equivalent
        # to ax.bbox but then ignore these properties during draws.
        noclip = (_AxesBase, maxis.Axis,
                  offsetbox.AnnotationBbox, offsetbox.OffsetBox)
        return [a for a in artists if a.get_visible() and a.get_in_layout()
                and (isinstance(a, noclip) or not a._fully_clipped_to_axes())]
`

This removes a large number of artists from the bounding box calculation. The test can use get_children() directly instead to test if 4 instances _Arrow3D exist.
